### PR TITLE
Counters change to AtomicLong

### PR DESCRIPTION
**Pull request by YijiaJin**
Related to issue #44. Accurate number of counters without impact of running time.

### CODE REVIEW

**Comment by stagraqubole** [comment]
@YijiaJin This fixes #44 partly, any plans to pick up remaining tasks from it?

**Comment by vrajat** [comment]
cc @abhishekdas99 since @YijiaJin has finished her internship.

**Comment by abhishekdas99** [comment]
I will pick the rest of it

**Comment by abhishekdas99** [comment]
Will be done by metrics changes.

**Pull request closed without merging**
