### PR TITLE
Add support for AliyunOSSFileSystem

### PR DESCRIPTION
**Pull request by on99**
https://hadoop.apache.org/docs/current/hadoop-aliyun/tools/hadoop-aliyun/index.html

### CODE REVIEW

**Comment by on99** [comment]
We are using prestosql to query data stored on aliyun oss file system and want to use rubix for local cache, however, this is not supported out of the box. FYI, https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java#L289-L300

**Comment by on99** [comment]
`mvn install` was executed successfully from project root, but `mvn test` failed. I do not know how to pass the unit test in CI.

**Comment by on99** [comment]
`mvn test` generates log as follow

```
Results :

Failed tests:   testCacheMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testCacheMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testHealthMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testHealthMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testJvmMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testJvmMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testValidationMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testValidationMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  verifyMetricsAreNotReportedToJMX(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  verifyMetricsAreRemoved(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  verifyMetricsAreReportedToJMX(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  verifyStatsDReporterIsReporting_onMaster_doNotReportOnMaster(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  verifyStatsDReporterIsReporting_onMaster_reportOnMaster(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  verifyStatsDReporterIsReporting_onWorker_doNotReportOnWorker(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  verifyStatsDReporterIsReporting_onWorker_reportOnWorker(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
  testWorkerHealthMetrics(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
  testWorkerHealthMetrics_healthStatusExpired(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
  testWorkerHealthMetrics_validatedWorkersMetricsNotRegisteredWhenValidationDisabled(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
  testWorkerHealthMetrics_validatedWorkersMetricsRegisteredWhenValidationEnabled(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
  setUp(com.qubole.rubix.bookkeeper.TestFileDownloader): org/apache/thrift/shaded/TException
  setUp(com.qubole.rubix.bookkeeper.TestRemoteFetchProcessor): org/apache/thrift/shaded/TException
  setUp(com.qubole.rubix.bookkeeper.TestWorkerBookKeeper): org/apache/thrift/shaded/transport/TTransportException

Tests run: 66, Failures: 22, Errors: 0, Skipped: 33

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for rubix 0.3.12-SNAPSHOT:
[INFO]
[INFO] rubix .............................................. SUCCESS [  0.058 s]
[INFO] rubix-spi .......................................... SUCCESS [ 11.150 s]
[INFO] rubix-common ....................................... SUCCESS [  0.868 s]
[INFO] rubix-core ......................................... SUCCESS [  0.856 s]
[INFO] rubix-client ....................................... SUCCESS [  0.352 s]
[INFO] rubix-presto ....................................... SUCCESS [  1.762 s]
[INFO] rubix-prestosql .................................... SUCCESS [  1.515 s]
[INFO] rubix-hadoop2 ...................................... SUCCESS [  1.383 s]
[INFO] rubix-bookkeeper ................................... FAILURE [  7.528 s]
[INFO] rubix-tests ........................................ SKIPPED
[INFO] assembly ........................................... SKIPPED
[INFO] rubix-rpm .......................................... SKIPPED
[INFO] rubix-presto-shaded ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.596 s
[INFO] Finished at: 2020-06-17T19:21:15+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project rubix-bookkeeper: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/on99/workspace/rubix/rubix-bookkeeper/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :rubix-bookkeeper
>>> elapsed time 27s
```

According to `[INFO] rubix-prestosql .................................... SUCCESS [  1.515 s]`, is the failed unit test really related to my commit? 

Please help, thank you!

**Comment by stagraqubole** [comment]
> `mvn test` generates log as follow
> 
> ```
> Results :
> 
> Failed tests:   testCacheMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testCacheMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testHealthMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testHealthMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testJvmMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testJvmMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testValidationMetricsEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testValidationMetricsNotEnabled(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   verifyMetricsAreNotReportedToJMX(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   verifyMetricsAreRemoved(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   verifyMetricsAreReportedToJMX(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   verifyStatsDReporterIsReporting_onMaster_doNotReportOnMaster(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   verifyStatsDReporterIsReporting_onMaster_reportOnMaster(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   verifyStatsDReporterIsReporting_onWorker_doNotReportOnWorker(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   verifyStatsDReporterIsReporting_onWorker_reportOnWorker(com.qubole.rubix.bookkeeper.TestBookKeeperServer): org/apache/thrift/shaded/transport/TTransportException
>   testWorkerHealthMetrics(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
>   testWorkerHealthMetrics_healthStatusExpired(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
>   testWorkerHealthMetrics_validatedWorkersMetricsNotRegisteredWhenValidationDisabled(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
>   testWorkerHealthMetrics_validatedWorkersMetricsRegisteredWhenValidationEnabled(com.qubole.rubix.bookkeeper.TestCoordinatorBookKeeper): org/apache/thrift/shaded/TException
>   setUp(com.qubole.rubix.bookkeeper.TestFileDownloader): org/apache/thrift/shaded/TException
>   setUp(com.qubole.rubix.bookkeeper.TestRemoteFetchProcessor): org/apache/thrift/shaded/TException
>   setUp(com.qubole.rubix.bookkeeper.TestWorkerBookKeeper): org/apache/thrift/shaded/transport/TTransportException
> 
> Tests run: 66, Failures: 22, Errors: 0, Skipped: 33
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for rubix 0.3.12-SNAPSHOT:
> [INFO]
> [INFO] rubix .............................................. SUCCESS [  0.058 s]
> [INFO] rubix-spi .......................................... SUCCESS [ 11.150 s]
> [INFO] rubix-common ....................................... SUCCESS [  0.868 s]
> [INFO] rubix-core ......................................... SUCCESS [  0.856 s]
> [INFO] rubix-client ....................................... SUCCESS [  0.352 s]
> [INFO] rubix-presto ....................................... SUCCESS [  1.762 s]
> [INFO] rubix-prestosql .................................... SUCCESS [  1.515 s]
> [INFO] rubix-hadoop2 ...................................... SUCCESS [  1.383 s]
> [INFO] rubix-bookkeeper ................................... FAILURE [  7.528 s]
> [INFO] rubix-tests ........................................ SKIPPED
> [INFO] assembly ........................................... SKIPPED
> [INFO] rubix-rpm .......................................... SKIPPED
> [INFO] rubix-presto-shaded ................................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  25.596 s
> [INFO] Finished at: 2020-06-17T19:21:15+08:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project rubix-bookkeeper: There are test failures.
> [ERROR]
> [ERROR] Please refer to /Users/on99/workspace/rubix/rubix-bookkeeper/target/surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :rubix-bookkeeper
> >>> elapsed time 27s
> ```
> 
> According to `[INFO] rubix-prestosql .................................... SUCCESS [ 1.515 s]`, is the failed unit test really related to my commit?
> 
> Please help, thank you!

Thanks for the contribution @on99 
This failure is not related to your change. I have checked it locally on my system and things look good. We need to fix the pipeline.

**Pull request merged**
