### PR TITLE
Document hadoop2 plugin usage

### PR DESCRIPTION
**Pull request by sakshia125**

### CODE REVIEW

**Comment by vrajat** [comment]
@abhishekdas99 @stagraqubole This seems like useful documentation. Worthwhile to polish and commit ? @abhishekdas99  I have assigned it to you to review and commit.

**Comment by stagraqubole** [comment]
This wasnt merged mainly due to reference to HADOOP_CUSTOM_OVERRIDES which is not used in oss hadoop.

**Comment by vrajat** [comment]
Is this a doc problem only ? Or is there work required to support OSS Hadoop2 ?

**Comment by stagraqubole** [comment]
Just the doc problem, if we provide the right config in core-site.xml, then we dont need to set it via system args.

**Comment by stagraqubole** [comment]
But if the requirement is to use Rubix only for client (say presto) but not for hadoop, then we need to find a way where hadoop conf can be set as part of hadoop jar command

**Pull request closed without merging**
