### PR TITLE
new: dev: RUB-219: Add support for ABFS

### PR DESCRIPTION
**Pull request by suryanshagnihotri**

### CODE REVIEW

**Comment by kvankayala** [comment]
@suryanshagnihotri How did you test the changes?

**Comment by suryanshagnihotri** [comment]
@kvankayala  I tested by replacing the rubix-presto jar in presto cluster with corresponding changes in presto for using newly added files.

**Comment by kvankayala** [comment]
@suryanshagnihotri And, Can you also make changes to support hadoop2/Spark? 

For your reference, https://github.com/qubole/rubix/pull/303/files

**Comment by suryanshagnihotri** [comment]
@kvankayala  will make changes there too.

**Pull request merged**
